name: Build and Distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: get and extract files
        run: |
          cat splitfile* > Runner.ipa.zip
          unzip Runner.ipa.zip

      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: Runner.ipa
      
      - name: Upload using iTMSTransporter
        env:
          WORKING_DIRECTORY: .
          IPA_FILE_NAME: Runner.ipa
          APPLE_USERNAME: vfijxvyz@outlook.com
          APPLE_PASSWORD: lxlv-stcz-itcg-iusp
          APPLE_ASC_PROVIDER: 4W7A8Z2X9R

        run: |
          cd $WORKING_DIRECTORY
          git clone https://github.com/ZhangLi1984/itsm.git
          ./itsm/bin/iTMSTransporter -assetFile $IPA_FILE_NAME -u $APPLE_USERNAME -p $APPLE_PASSWORD -m upload -asc_provider $APPLE_ASC_PROVIDER
